import { useEffect, useRef, useState } from 'react'
import type { Section } from '../components/navigation'
import { Icon } from '../components/Icon'
import { TopBar } from '../components/TopBar'
import { PrimaryButton, SecondaryButton } from '../components/Primitives'
import { useAuth } from '../state/AuthProvider'
import { useToast } from '../components/Toast'
import { samNext, samSummary, AiError, type Turn } from '../lib/ai'
import { createReflection } from '../lib/reflections'

// Prefer the Edge Function's friendly message (e.g. the daily limit) over a
// generic fallback.
function aiMessage(e: unknown): string {
  return e instanceof AiError && e.userMessage ? e.userMessage : "Sam couldn't respond just now."
}

const MAX_QUESTIONS = 5

// A fixed, warm opener (shown instantly with a few suggestions); every question
// after this is generated by Sam, adapting to the person's answers.
const OPENER = {
  text: 'When do you feel most at ease with another person?',
  chips: ['In easy silence', 'Over a shared meal', 'On a long walk', "When we're laughing"],
}

// 'paused' means an AI step was interrupted (e.g. a refresh mid-thought) and
// needs an explicit "Continue with Sam" — we never auto-fire an AI call on load.
type Phase = 'asking' | 'thinking' | 'summarizing' | 'error' | 'paused'
type Pending = 'next' | 'summary' | null

// The whole Sam session is kept in per-tab, user-scoped sessionStorage so it
// survives refresh but stays private and separate from permanent Reflections.
interface Snapshot {
  turns: Turn[]
  currentQuestion: string
  summary: string | null
  saved: boolean
  pending: Pending
}

function loadSnapshot(key: string | null): Snapshot | null {
  if (!key) return null
  try {
    const raw = sessionStorage.getItem(key)
    if (!raw) return null
    const s = JSON.parse(raw) as Snapshot
    if (!Array.isArray(s.turns)) return null
    return s
  } catch {
    return null
  }
}

function SamPage({ onNavigate }: { onNavigate: (s: Section) => void }) {
  const { user } = useAuth()
  const key = user?.id ? `mosaic:sam:${user.id}` : null

  const [initial] = useState(() => loadSnapshot(key))
  const [turns, setTurns] = useState<Turn[]>(initial?.turns ?? [])
  const [currentQuestion, setCurrentQuestion] = useState(initial?.currentQuestion ?? OPENER.text)
  const [summary, setSummary] = useState<string | null>(initial?.summary ?? null)
  const [saved, setSaved] = useState<boolean>(initial?.saved ?? false)
  const [pending, setPending] = useState<Pending>(initial?.pending ?? null)
  // If we hydrated an interrupted AI step, start paused (explicit Continue).
  const [phase, setPhase] = useState<Phase>(
    initial && initial.summary === null && initial.pending ? 'paused' : 'asking',
  )
  const [draft, setDraft] = useState('')
  const [errorMsg, setErrorMsg] = useState<string | null>(null)
  const retryRef = useRef<(() => void) | null>(null)
  const endRef = useRef<HTMLDivElement>(null)

  // Persist the session to sessionStorage whenever it changes.
  useEffect(() => {
    if (!key) return
    const snap: Snapshot = { turns, currentQuestion, summary, saved, pending }
    try {
      sessionStorage.setItem(key, JSON.stringify(snap))
    } catch {
      // storage full/unavailable — the session simply won't persist
    }
  }, [key, turns, currentQuestion, summary, saved, pending])

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [turns, phase, summary])

  const askNext = async (history: Turn[]) => {
    setPending('next')
    setPhase('thinking')
    try {
      const { question, done } = await samNext(history)
      if (done || !question.trim()) {
        summarize(history)
      } else {
        setPending(null)
        setCurrentQuestion(question)
        setPhase('asking')
      }
    } catch (e) {
      retryRef.current = () => askNext(history)
      setErrorMsg(aiMessage(e))
      setPhase('error')
    }
  }

  const summarize = async (history: Turn[]) => {
    setPending('summary')
    setPhase('summarizing')
    try {
      const { summary: text } = await samSummary(history)
      setPending(null)
      setSummary(text)
    } catch (e) {
      retryRef.current = () => summarize(history)
      setErrorMsg(aiMessage(e))
      setPhase('error')
    }
  }

  // Record an answer for the current question, then advance or summarize.
  const submit = (text: string) => {
    const next = [...turns, { q: currentQuestion, a: text }]
    setTurns(next)
    setDraft('')
    if (next.length >= MAX_QUESTIONS) summarize(next)
    else askNext(next)
  }

  const answer = (text: string) => {
    if (!text.trim() || phase !== 'asking') return
    submit(text)
  }

  // Explicit resume after an interrupted step — no automatic AI call on load.
  const resume = () => {
    if (pending === 'summary') summarize(turns)
    else askNext(turns)
  }

  const restart = () => {
    if (key) sessionStorage.removeItem(key)
    setTurns([])
    setCurrentQuestion(OPENER.text)
    setSummary(null)
    setSaved(false)
    setPending(null)
    setPhase('asking')
    setDraft('')
  }

  if (summary !== null) {
    return (
      <SamSummary
        summary={summary}
        saved={saved}
        onSaved={() => setSaved(true)}
        onViewSaved={() => onNavigate('reflections')}
        onRestart={restart}
      />
    )
  }

  const questionNumber = Math.min(turns.length + 1, MAX_QUESTIONS)

  return (
    <div className="sam">
      <TopBar title="Sam, your Mosaic guide" />

      <div className="sam-thread">
        <div className="wrap sam-list">
          <div className="sam-msg-row">
            <SamAvatar />
            <div>
              <p className="sam-name">
                Sam <span className="muted">· Your Mosaic Guide</span>
              </p>
              <div className="sam-bubble">
                Hi, I'm Sam — a private reflection companion. I'm not a matchmaker or
                therapist. I'll ask a few gentle questions to help you notice what matters to
                you. Take your time.
              </div>
            </div>
          </div>

          {turns.map((t, i) => (
            <div key={i} className="sam-turn">
              <div className="sam-msg-row">
                <SamAvatar />
                <div className="sam-bubble">{t.q}</div>
              </div>
              <div className="sam-me-row">
                <div className="sam-bubble sam-bubble-me">{t.a}</div>
              </div>
            </div>
          ))}

          {phase === 'asking' && (
            <div className="sam-msg-row">
              <SamAvatar />
              <div className="sam-bubble">{currentQuestion}</div>
            </div>
          )}

          {(phase === 'thinking' || phase === 'summarizing') && (
            <div className="sam-msg-row">
              <SamAvatar />
              <div className="sam-bubble sam-typing" aria-label="Sam is thinking">
                {phase === 'summarizing' ? 'Gathering your reflection…' : 'Sam is thinking…'}
              </div>
            </div>
          )}

          {phase === 'paused' && (
            <div className="sam-msg-row">
              <SamAvatar />
              <div className="sam-bubble">
                <p>We paused here — ready when you are.</p>
                <button type="button" className="pill-btn sam-continue" onClick={resume}>
                  <Icon name="message" size={16} />
                  Continue with Sam
                </button>
              </div>
            </div>
          )}

          {phase === 'error' && (
            <div className="sam-msg-row">
              <SamAvatar />
              <div className="sam-bubble">
                <p className="auth-error" role="alert">
                  {errorMsg ?? "Sam couldn't respond just now."}
                </p>
                <button
                  type="button"
                  className="pill-btn"
                  onClick={() => retryRef.current?.()}
                >
                  <Icon name="rotate" size={16} />
                  Try again
                </button>
              </div>
            </div>
          )}

          <div ref={endRef} />
        </div>
      </div>

      <div className="sam-composer">
        <div className="wrap sam-composer-inner">
          <div className="between">
            <span className="count">
              Question {questionNumber} of {MAX_QUESTIONS}
            </span>
            <button
              type="button"
              className="pill-btn small-pill"
              onClick={() => answer('(skipped)')}
              disabled={phase !== 'asking'}
            >
              <Icon name="skip" size={16} />
              Skip
            </button>
          </div>

          {turns.length === 0 && phase === 'asking' && (
            <div className="chip-wrap">
              {OPENER.chips.map((c) => (
                <button
                  key={c}
                  type="button"
                  className="chip chip-select"
                  onClick={() => answer(c)}
                >
                  {c}
                </button>
              ))}
            </div>
          )}

          <form
            className="sam-input-row"
            onSubmit={(e) => {
              e.preventDefault()
              answer(draft)
            }}
          >
            <label className="sr-only" htmlFor="sam-input">
              Your answer
            </label>
            <input
              id="sam-input"
              className="input"
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              placeholder="Write your own answer…"
              disabled={phase !== 'asking'}
            />
            <button
              type="submit"
              className="send-btn"
              disabled={!draft.trim() || phase !== 'asking'}
              aria-label="Send answer"
            >
              <Icon name="send" />
            </button>
          </form>

          <p className="note">
            <Icon name="lock" size={14} />
            This conversation is private. Sam supports reflection and self-exploration — not
            therapy, crisis support, or professional advice.
          </p>
        </div>
      </div>
    </div>
  )
}

function SamAvatar() {
  return (
    <span className="sam-avatar" aria-hidden="true">
      <Icon name="sparkles" size={16} />
    </span>
  )
}

// Closing screen: the AI summary. Saving is optional and permanent; after
// saving it shows a saved state (no auto-navigate, no accidental re-save).
function SamSummary({
  summary,
  saved,
  onSaved,
  onViewSaved,
  onRestart,
}: {
  summary: string
  saved: boolean
  onSaved: () => void
  onViewSaved: () => void
  onRestart: () => void
}) {
  const { user } = useAuth()
  const toast = useToast()
  const [saving, setSaving] = useState(false)

  const save = async () => {
    if (!user || saving) return
    setSaving(true)
    try {
      await createReflection(user.id, { prompt: 'A reflection with Sam', body: summary })
      toast({
        title: 'Saved to your reflections',
        description: 'You can generate a Connection Lens from it there.',
      })
      onSaved()
    } catch {
      toast({ title: "We couldn't save that", description: 'Please try again.' })
    } finally {
      setSaving(false)
    }
  }

  return (
    <div>
      <TopBar title="Your reflection with Sam" showBack onBack={onRestart} />

      <main className="wrap page-main">
        <div className="lens-hero">
          <span className="lens-hero-icon">
            <Icon name="sparkles" size={24} />
          </span>
          <h2 className="lens-hero-title">A gentle summary</h2>
          <p className="muted">Here's what you seemed to notice together.</p>
        </div>

        <div className="prompt-box">
          <p className="reflection-body">{summary}</p>
        </div>

        <p className="center muted small">
          Sam supports reflection and self-exploration — not therapy, crisis support,
          diagnosis, or professional advice.
        </p>

        {saved ? (
          <>
            <p className="note">
              <Icon name="check" size={16} />
              Saved to your reflections.
            </p>
            <div className="btn-row">
              <SecondaryButton onClick={onRestart}>
                <Icon name="rotate" />
                Start a new conversation
              </SecondaryButton>
              <PrimaryButton onClick={onViewSaved}>View saved reflection</PrimaryButton>
            </div>
          </>
        ) : (
          <div className="btn-row">
            <SecondaryButton onClick={onRestart}>
              <Icon name="rotate" />
              Start again
            </SecondaryButton>
            <PrimaryButton onClick={save} disabled={saving}>
              {saving ? 'Saving…' : 'Save to my reflections'}
            </PrimaryButton>
          </div>
        )}
      </main>
    </div>
  )
}

export default SamPage
